name: Build NativeAOT

on:
  release:
    types: [created] 

permissions:
  contents: write

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish AOT
        run: dotnet publish CFWeaver/CFWeaver.csproj -c Release -r linux-x64 -o output/linux-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfweaver-linux-x64
          path: output/linux-x64

#  TODO: make this work
#  build-linux-arm64:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Install Dependencies for Cross Compilation
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y qemu-user-static binfmt-support
#          sudo update-binfmts --enable qemu-aarch64
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: 9.0.x
#
#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Publish AOT for Linux ARM64
#        run: |
#          sudo apt-get install -y clang llvm
#          dotnet publish CFWeaver/CFWeaver.csproj -c Release -r linux-arm64 -o output/linux-arm64
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: cfweaver-linux-arm64
#          path: output/linux-arm64

  build-windows-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish AOT
        run: dotnet publish CFWeaver/CFWeaver.csproj -c Release -r win-x86 -o output/win-x86

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfweaver-win-x86
          path: output/win-x86

  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish AOT
        run: dotnet publish CFWeaver/CFWeaver.csproj -c Release -r win-x64 -o output/win-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfweaver-win-x64
          path: output/win-x64

  build-windows-arm64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish AOT
        run: dotnet publish CFWeaver/CFWeaver.csproj -c Release -r win-arm64 -o output/win-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfweaver-win-arm64
          path: output/win-arm64

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish AOT
        run: dotnet publish CFWeaver/CFWeaver.csproj -c Release -r osx-x64 -o output/osx-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfweaver-osx-x64
          path: output/osx-x64

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish AOT
        run: dotnet publish CFWeaver/CFWeaver.csproj -c Release -r osx-arm64 -o output/osx-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: osx-arm64
          path: output/osx-arm64

  release:
    needs: [build-linux-x64, build-windows-x86, build-windows-x64, build-windows-arm64, build-macos-x64, build-macos-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Artifacts
        run: |
          cd artifacts
          for dir in *; do
            if [ -d "$dir" ]; then
            zip -r "${dir}.zip" "$dir"
            fi
          done
          ls -lh
  
      - name: Upload Zips to Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}