name: Build NativeAOT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: ubuntu-latest
            rid: linux-arm64
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-arm64
          - os: macos-latest
            rid: osx-x64
          - os: macos-latest
            rid: osx-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Remove previous artifacts
        run: rm -rf output/${{ matrix.rid }}

      - name: Publish AOT
        run: dotnet publish -c Release -r ${{ matrix.rid }} -o output/${{ matrix.rid }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.rid }}-${{ github.run_id }}
          path: output/${{ matrix.rid }}